export const FEED_ADD_COMMENT = 'FEED-ADD-COMMENT';
export const FEED_ESTIMATE_THIS_POST = 'FEED-ESTIMATE-THIS-POST';
export const FEED_SET_NEW_STATE = 'FEED-SET-NEW-STATE';
export const SET_TOTAL_COUNT = 'SET-TOTAL-COUNT';
